# Generated by Django 5.1.6 on 2025-02-15 01:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0002_employee_regular_date_employee_separation_date'),
        ('items', '0002_itempriceadjustment_unique_item_date'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transact_creator', to='employees.employee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacts.transactstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TransactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transact_item', to='items.item')),
                ('transact_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transacts.transactheader')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactheader',
            constraint=models.UniqueConstraint(fields=('si_no', 'company'), name='unique_transact'),
        ),
    ]
