# Generated by Django 5.1.6 on 2025-02-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_regular_date_employee_separation_date'),
        ('transacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactheader',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact_creator', to='employees.employee'),
        ),
    ]
