# Generated by Django 5.1.6 on 2025-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itempriceadjustment',
            constraint=models.UniqueConstraint(fields=('item', 'date'), name='unique_item_date'),
        ),
    ]
