# Generated by Django 5.1.6 on 2025-02-13 05:57

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[
                 ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True,
                 validators=[employees.models.validate_age])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeejob')),
                ('position_level', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeejoblevel')),
                ('position_specialties', models.ManyToManyField(
                    blank=True, to='employees.employeejobspecialty')),
                ('status', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeestatus')),
            ],
        ),
    ]
